package objectorientedprogramming;

/**
 *
 * @author Charvi
 */
public class Pizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizza
     */
    static int total_cost=0;
    public Pizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pizza = new javax.swing.JPanel();
        Small = new javax.swing.JRadioButton();
        Medium = new javax.swing.JRadioButton();
        Large = new javax.swing.JRadioButton();
        Toppings = new javax.swing.JPanel();
        Plain = new javax.swing.JCheckBox();
        Sausage = new javax.swing.JCheckBox();
        Mushroom = new javax.swing.JCheckBox();
        Pepperoni = new javax.swing.JCheckBox();
        CostButton = new javax.swing.JButton();
        Display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radio Button Programming");

        Pizza.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Size"));

        Small.setText("Small");
        Small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallActionPerformed(evt);
            }
        });

        Medium.setText("Medium");
        Medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumActionPerformed(evt);
            }
        });

        Large.setText("Large");
        Large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PizzaLayout = new javax.swing.GroupLayout(Pizza);
        Pizza.setLayout(PizzaLayout);
        PizzaLayout.setHorizontalGroup(
            PizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Small)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Medium)
                .addGap(40, 40, 40)
                .addComponent(Large)
                .addGap(34, 34, 34))
        );
        PizzaLayout.setVerticalGroup(
            PizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Small)
                    .addComponent(Medium)
                    .addComponent(Large))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Toppings.setBorder(javax.swing.BorderFactory.createTitledBorder("Toppings"));

        Plain.setText("Plain");
        Plain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlainActionPerformed(evt);
            }
        });

        Sausage.setText("Sausage");
        Sausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SausageActionPerformed(evt);
            }
        });

        Mushroom.setText("Mushroom");
        Mushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MushroomActionPerformed(evt);
            }
        });

        Pepperoni.setText("Pepperoni");
        Pepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepperoniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToppingsLayout = new javax.swing.GroupLayout(Toppings);
        Toppings.setLayout(ToppingsLayout);
        ToppingsLayout.setHorizontalGroup(
            ToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToppingsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pepperoni)
                    .addGroup(ToppingsLayout.createSequentialGroup()
                        .addComponent(Plain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sausage)
                        .addGap(18, 18, 18)
                        .addComponent(Mushroom)))
                .addContainerGap())
        );
        ToppingsLayout.setVerticalGroup(
            ToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToppingsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Plain)
                    .addComponent(Sausage)
                    .addComponent(Mushroom))
                .addGap(18, 18, 18)
                .addComponent(Pepperoni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CostButton.setText("Calculate Total Cost");
        CostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(Toppings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(CostButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Toppings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CostButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlainActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+0;
    }//GEN-LAST:event_PlainActionPerformed

    private void SmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+100;
    }//GEN-LAST:event_SmallActionPerformed

    private void MediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+130;
    }//GEN-LAST:event_MediumActionPerformed

    private void LargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargeActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+160;
    }//GEN-LAST:event_LargeActionPerformed

    private void SausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SausageActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+20;
    }//GEN-LAST:event_SausageActionPerformed

    private void MushroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MushroomActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+20;
    }//GEN-LAST:event_MushroomActionPerformed

    private void PepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepperoniActionPerformed
        // TODO add your handling code here:
        total_cost=total_cost+20;
    }//GEN-LAST:event_PepperoniActionPerformed

    private void CostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostButtonActionPerformed
        // TODO add your handling code here:
        Display.setText("Total cost is Rs."+total_cost);
        total_cost=0;
        Plain.setSelected(false);
        Sausage.setSelected(false);
        Mushroom.setSelected(false);
        Pepperoni.setSelected(false);
        Small.setSelected(false);
        Medium.setSelected(false);
        Large.setSelected(false);        
        
    }//GEN-LAST:event_CostButtonActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CostButton;
    private javax.swing.JTextField Display;
    private javax.swing.JRadioButton Large;
    private javax.swing.JRadioButton Medium;
    private javax.swing.JCheckBox Mushroom;
    private javax.swing.JCheckBox Pepperoni;
    private javax.swing.JPanel Pizza;
    private javax.swing.JCheckBox Plain;
    private javax.swing.JCheckBox Sausage;
    private javax.swing.JRadioButton Small;
    private javax.swing.JPanel Toppings;
    // End of variables declaration//GEN-END:variables
}
